#!/bin/bash

echo "Cloning .vim"

git clone git@github.com:arnm/.vim.git  ~/.vim

echo "Downloading vim-plug"

mkdir ~/.vim/autoload
curl -fLo ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

ln -s ~/.vim/vimrc ~/.vimrc

echo ".vim Bootstrap Complete"
