#!/bin/bash

echo "Downloading vim-plug"

mkdir -p ~/.vim/autoload
curl -fLo ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Cloning .vim"

git clone https://github.com/arnm/.vim ~/.vim

echo ".vim Bootstrap Complete"
